badScroll:
	g++ -std=c++11 -g -I /usr/local/Cellar/xerces-c/3.2.3/include -L /usr/local/Cellar/xerces-c/3.2.3/lib ObjectDisplayGrid.cpp dungeon.cpp displayable.cpp scrolly.cpp action.cpp main.cpp badXMLHandler.cpp GridChar.cpp KeyboardListener.cpp -o test -lxerces-c -lncurses
	./test badScroll.xml
testDrawing:
	g++ -std=c++11 -g -I /usr/local/Cellar/xerces-c/3.2.3/include -L /usr/local/Cellar/xerces-c/3.2.3/lib ObjectDisplayGrid.cpp dungeon.cpp displayable.cpp action.cpp draw.cpp main.cpp badXMLHandler.cpp GridChar.cpp KeyboardListener.cpp -o test -lxerces-c -lncurses
	./test testDrawing.xml
dropPack:
	g++ -std=c++11 -g -I /usr/local/Cellar/xerces-c/3.2.3/include -L /usr/local/Cellar/xerces-c/3.2.3/lib ObjectDisplayGrid.cpp dungeon.cpp displayable.cpp action.cpp drop.cpp main.cpp badXMLHandler.cpp GridChar.cpp KeyboardListener.cpp -o test -lxerces-c -lncurses
	./test dropPack.xml
death:
	g++ -std=c++11 -g -I /usr/local/Cellar/xerces-c/3.2.3/include -L /usr/local/Cellar/xerces-c/3.2.3/lib ObjectDisplayGrid.cpp dungeon.cpp displayable.cpp action.cpp bye.cpp main.cpp badXMLHandler.cpp GridChar.cpp KeyboardListener.cpp -o test -lxerces-c -lncurses
	./test death.xml
dungeon:
	g++ -std=c++11 -g -I /usr/local/Cellar/xerces-c/3.2.3/include -L /usr/local/Cellar/xerces-c/3.2.3/lib ObjectDisplayGrid.cpp dungeon.cpp displayable.cpp action.cpp dungy.cpp main.cpp badXMLHandler.cpp GridChar.cpp KeyboardListener.cpp -o test -lxerces-c -lncurses
	./test dungeon.xml
hallucinate:
	g++ -std=c++11 -g -I /usr/local/Cellar/xerces-c/3.2.3/include -L /usr/local/Cellar/xerces-c/3.2.3/lib ObjectDisplayGrid.cpp dungeon.cpp displayable.cpp action.cpp holly.cpp main.cpp badXMLHandler.cpp GridChar.cpp KeyboardListener.cpp -o test -lxerces-c -lncurses
	./test hallucinate.xml
clean:
	rm -f main